@apiVersion = v1
@host = http://localhost:3000/api/{{apiVersion}}
@contentType = application/json

# User
@name = [string]
@email = [string]
@password = 5fC5gda@
@birthDate = 1990-10-08

# Token JWT (Email Confirmation)
@token = 

### Create User
POST {{host}}/clients
Content-Type: {{contentType}}

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "passwordConfirmation": "{{password}}",
    "birthDate": "{{birthDate}}"
}

### Confirm Email
GET  {{host}}/email/confirmation?token={{token}}

### Authenticate User
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}
