@apiVersion = v1
@host = http://localhost:3000/api/{{apiVersion}}
@contentType = application/json

# User
@name = [string]
@email = [string]
@password = 5fC5gda@
@birthDate = 1990-10-08

@access_token = {{UserToken.response.body.access_token}}

# Token JWT (Email Confirmation)
@token =

### Create User Client
# @name UserToken
POST {{host}}/auth/register
Content-Type: {{contentType}}

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "passwordConfirmation": "{{password}}",
    "birthDate": "{{birthDate}}",
    "termsAccepted": true
}

### Create User Artist
# @name UserToken
POST {{host}}/auth/register/artist
Content-Type: {{contentType}}

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "passwordConfirmation": "{{password}}",
    "birthDate": "{{birthDate}}",
    "termsAccepted": true,
    "address": {
      "street": "Rua 1",
      "number": "123",
      "city": "São Paulo",
      "state": "SP",
      "country": "Brasil",
      "zipCode": "12345678"
    }
}

### Confirm Email
GET  {{host}}/email/confirmation?token={{token}}

### Authenticate User
# @name UserToken
POST {{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}
