@host = http://localhost:3000
@apiVersion = v1
@contentType = application/json

# User
@name = João Silva
@email = 
@password = Jo@o2023
@birthDate = 2000-10-02

# Token JWT (Email Confirmation)
@token = 

### Create User
POST {{host}}/api/{{apiVersion}}/clients
Content-Type: {{contentType}}

{
    "name": "{{name}}",
    "email": "{{email}}",
    "password": "{{password}}",
    "passwordConfirmation": "{{password}}",
    "birthDate": "{{birthDate}}"
}

### Confirm Email
GET  {{host}}/api/{{apiVersion}}/email/confirmation?token={{token}}
