name: connectattoo

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    restart: 'on-failure'
    env_file:
      - .env
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 5555:5555
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - connectattoo
    volumes:
      - .:/api
    entrypoint: sh -c "./.docker/entrypoint.sh"

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - connectattoo
    volumes:
      - ./.docker/postgres/init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d connectattoo -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8082:8080
    networks:
      - connectattoo
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DEFAULT_SYSTEM=pgsql
      - ADMINER_DESIGN=hydra

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
    env_file:
      - .env
    volumes:
      - ./.docker/localstack/entrypoint.sh:/etc/localstack/init/ready.d/entrypoint.sh
    networks:
      - connectattoo

networks:
  connectattoo:
    name: connectattoo
    driver: bridge
